spring:
  application:
    name: demo-admin-client
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:8001
server:
  port: 8002
management:
  endpoints:
    web:
      exposure:
        include: "*"
